/**
 * Minimal, valid PDF report writer (M6 exports — zero-dependency by design).
 * Base-14 Helvetica/Helvetica-Bold fonts (no embedding), one content stream
 * per page, repeated table header, exact byte-offset xref table. Sanitization
 * is part of correctness here: text is reduced to printable Latin-1 (PDF
 * WinAnsi for these fonts), parens/backslashes escaped.
 */

import type { CsvCell } from "./csv";

const PAGE_WIDTH = 612; // US Letter, portrait
const PAGE_HEIGHT = 792;
const MARGIN = 40;
const TITLE_SIZE = 13;
const BODY_SIZE = 8;
const ROW_HEIGHT = 13;
const HEADER_GAP = 20;
const CHAR_WIDTH_FACTOR = 0.52; // Helvetica avg advance for 8pt caps/digits mix
const MAX_COLUMNS = 12;

export interface PdfTableInput {
  readonly title: string;
  readonly subtitle?: string;
  readonly headers: readonly string[];
  readonly rows: readonly (readonly CsvCell[])[];
}

function sanitizeText(value: string): string {
  let out = "";
  for (const char of value) {
    const code = char.codePointAt(0) ?? 63;
    out += code >= 32 && code <= 126 ? char : code === 8230 ? "..." : "?";
  }
  return out;
}

function pdfEscape(value: string): string {
  return sanitizeText(value).replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
}

function truncateToWidth(value: string, widthPt: number, size: number): string {
  const maxChars = Math.max(1, Math.floor(widthPt / (size * CHAR_WIDTH_FACTOR)));
  const clean = sanitizeText(value);
  return clean.length <= maxChars ? clean : `${clean.slice(0, Math.max(1, maxChars - 1))}…`;
}

function cellText(cell: CsvCell): string {
  if (cell === null) return "";
  if (typeof cell === "number") return Number.isFinite(cell) ? String(cell) : "";
  return typeof cell === "boolean" ? (cell ? "TRUE" : "FALSE") : cell;
}

interface ColumnLayout {
  readonly width: number;
}

/** Column widths from content samples, capped, then scaled to the table width. */
function computeColumnWidths(headers: readonly string[], rows: readonly (readonly CsvCell[])[]): ColumnLayout[] {
  const tableWidth = PAGE_WIDTH - MARGIN * 2;
  const maxCol = Math.floor(tableWidth / Math.min(headers.length, 3));
  const natural = headers.map((header, index) => {
    let chars = header.length;
    for (const row of rows.slice(0, 200)) {
      const text = cellText(row[index] ?? null);
      if (text.length > chars) chars = text.length;
    }
    return Math.max(36, Math.min(maxCol, (Math.min(chars, 60) + 1) * BODY_SIZE * CHAR_WIDTH_FACTOR));
  });
  const total = natural.reduce((sum, w) => sum + w, 0);
  const scale = total > tableWidth ? tableWidth / total : 1;
  return natural.map((width) => ({ width: Math.max(28, width * scale) }));
}

interface PdfObject {
  readonly body: string;
}

/** Assemble the document with byte-exact offsets (the xref contract). */
function assemblePdf(objects: readonly PdfObject[]): Buffer {
  const chunks: Buffer[] = [];
  const offsets: number[] = [];
  let position = 0;
  const push = (buffer: Buffer): void => {
    chunks.push(buffer);
    position += buffer.length;
  };
  push(Buffer.from("%PDF-1.4\n", "latin1"));
  for (let i = 0; i < objects.length; i += 1) {
    offsets.push(position);
    push(Buffer.from(`${i + 1} 0 obj\n${objects[i]!.body}\nendobj\n`, "latin1"));
  }
  const xrefStart = position;
  const xrefLines = [`xref\n0 ${objects.length + 1}\n`, "0000000000 65535 f \n"];
  for (const offset of offsets) {
    xrefLines.push(`${offset.toString().padStart(10, "0")} 00000 n \n`);
  }
  push(Buffer.from(xrefLines.join(""), "latin1"));
  const trailer = `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;
  push(Buffer.from(trailer, "latin1"));
  return Buffer.concat(chunks);
}

function pageContentStream(
  input: PdfTableInput,
  columns: readonly ColumnLayout[],
  rows: readonly (readonly CsvCell[])[],
  pageNumber: number,
  totalPages: number,
): string {
  const ops: string[] = [];
  let cursorY = PAGE_HEIGHT - MARGIN;
  ops.push(`BT /F2 ${TITLE_SIZE} Tf ${MARGIN} ${cursorY} Td (${pdfEscape(input.title)}) Tj ET`);
  cursorY -= 16;
  const subtitle = `${input.subtitle ?? "Generated by PROFIT TOOL AI"}  ·  Page ${pageNumber} of ${totalPages}`;
  ops.push(`BT /F1 ${BODY_SIZE} Tf ${MARGIN} ${cursorY} Td (${pdfEscape(subtitle)}) Tj ET`);
  cursorY -= HEADER_GAP;

  const tableWidth = columns.reduce((sum, col) => sum + col.width, 0);
  // Header row.
  ops.push(`${MARGIN} ${cursorY - ROW_HEIGHT + 3} ${tableWidth} ${ROW_HEIGHT} re f 0.92 g`);
  ops.push("0 g");
  let cursorX = MARGIN;
  for (let i = 0; i < input.headers.length; i += 1) {
    const text = truncateToWidth(input.headers[i]!, columns[i]!.width - 6, BODY_SIZE);
    ops.push(`BT /F2 ${BODY_SIZE} Tf ${cursorX + 3} ${cursorY - ROW_HEIGHT + 7} Td (${pdfEscape(text)}) Tj ET`);
    cursorX += columns[i]!.width;
  }
  cursorY -= ROW_HEIGHT;

  for (const row of rows) {
    cursorX = MARGIN;
    for (let i = 0; i < input.headers.length; i += 1) {
      const text = truncateToWidth(cellText(row[i] ?? null), columns[i]!.width - 6, BODY_SIZE);
      ops.push(`BT /F1 ${BODY_SIZE} Tf ${cursorX + 3} ${cursorY - ROW_HEIGHT + 7} Td (${pdfEscape(text)}) Tj ET`);
      cursorX += columns[i]!.width;
    }
    // Hairline rule under the row.
    ops.push(`${MARGIN} ${cursorY - ROW_HEIGHT} ${tableWidth} 0.4 re f 0.88 g`);
    ops.push("0 g");
    cursorY -= ROW_HEIGHT;
  }
  return ops.join("\n");
}

/** Build the full PDF buffer (paginated table, header repeated per page). */
export function buildPdf(input: PdfTableInput): Buffer {
  if (input.headers.length === 0 || input.headers.length > MAX_COLUMNS) {
    throw new Error(`pdf: header count must be 1..${MAX_COLUMNS}`);
  }
  const columns = computeColumnWidths(input.headers, input.rows);
  const firstPageTop = PAGE_HEIGHT - MARGIN - 16 - HEADER_GAP;
  const rowsPerPage = Math.max(1, Math.floor((firstPageTop - MARGIN - ROW_HEIGHT) / ROW_HEIGHT));

  const pages: (readonly CsvCell[])[][] = [];
  for (let start = 0; start < input.rows.length; start += rowsPerPage) {
    pages.push(input.rows.slice(start, start + rowsPerPage));
  }
  if (pages.length === 0) pages.push([]);

  const objects: PdfObject[] = [];
  // Object 1: catalog. Object 2: pages. Objects 3..: per-page page+content pairs.
  const pageObjectIds: number[] = [];
  let nextId = 3;
  for (let p = 0; p < pages.length; p += 1) {
    pageObjectIds.push(nextId);
    nextId += 2;
  }
  // Font objects land after page objects.
  const fontRegularId = nextId;
  const fontBoldId = nextId + 1;

  objects.push({ body: "<< /Type /Catalog /Pages 2 0 R >>" });
  const kids = pageObjectIds.map((id) => `${id} 0 R`).join(" ");
  objects.push({ body: `<< /Type /Pages /Kids [ ${kids} ] /Count ${pageObjectIds.length} >>` });

  for (let p = 0; p < pages.length; p += 1) {
    const pageId = pageObjectIds[p]!;
    const contentId = pageId + 1;
    const stream = pageContentStream(input, columns, pages[p]!, p + 1, pageObjectIds.length);
    objects.push({
      body: `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${fontRegularId} 0 R /F2 ${fontBoldId} 0 R >> >> /Contents ${contentId} 0 R >>`,
    });
    objects.push({
      body: `<< /Length ${Buffer.byteLength(stream, "latin1")} >>\nstream\n${stream}\nendstream`,
    });
  }
  objects.push({ body: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>" });
  objects.push({ body: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>" });

  return assemblePdf(objects);
}
