/**
 * Minimal, valid PDF report writer (M6 exports — zero-dependency by design).
 * Base-14 Helvetica/Helvetica-Bold fonts (no embedding), one content stream
 * per page, repeated table header, exact byte-offset xref table. Sanitization
 * is part of correctness here: text is reduced to printable Latin-1 (PDF
 * WinAnsi for these fonts), parens/backslashes escaped.
 */

import type { CsvCell } from "./csv";

const PAGE_WIDTH = 612; // US Letter, portrait
const PAGE_HEIGHT = 792;
const MARGIN = 40;
const TITLE_SIZE = 13;
const BODY_SIZE = 8;
const ROW_HEIGHT = 13;
const HEADER_GAP = 20;
const CHAR_WIDTH_FACTOR = 0.52; // Helvetica avg advance for 8pt caps/digits mix
const MAX_COLUMNS = 12;

export interface PdfTableInput {
  readonly title: string;
  readonly subtitle?: string;
  readonly headers: readonly string[];
  readonly rows: readonly (readonly CsvCell[])[];
}

function sanitizeText(value: string): string {
  let out = "";
  for (const char of value) {
    const code = char.codePointAt(0) ?? 63;
    out += code >= 32 && code <= 126 ? char : code === 8230 ? "..." : "?";
  }
  return out;
}

function pdfEscape(value: string): string {
  return sanitizeText(value).replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
}

function truncateToWidth(value: string, widthPt: number, size: number): string {
  const maxChars = Math.max(1, Math.floor(widthPt / (size * CHAR_WIDTH_FACTOR)));
  const clean = sanitizeText(value);
  return clean.length <= maxChars ? clean : `${clean.slice(0, Math.max(1, maxChars - 1))}…`;
}

function cellText(cell: CsvCell): string {
  if (cell === null) return "";
  if (typeof cell === "number") return Number.isFinite(cell) ? String(cell) : "";
  return typeof cell === "boolean" ? (cell ? "TRUE" : "FALSE") : cell;
}

interface ColumnLayout {
  readonly width: number;
}

/** Column widths from content samples, capped, then scaled to the table width. */
function computeColumnWidths(headers: readonly string[], rows: readonly (readonly CsvCell[])[]): ColumnLayout[] {
  const tableWidth = PAGE_WIDTH - MARGIN * 2;
  const maxCol = Math.floor(tableWidth / Math.min(headers.length, 3));
  const natural = headers.map((header, index) => {
    let chars = header.length;
    for (const row of rows.slice(0, 200)) {
      const text = cellText(row[index] ?? null);
      if (text.length > chars) chars = text.length;
    }
    return Math.max(36, Math.min(maxCol, (Math.min(chars, 60) + 1) * BODY_SIZE * CHAR_WIDTH_FACTOR));
  });
  const total = natural.reduce((sum, w) => sum + w, 0);
  const scale = total > tableWidth ? tableWidth / total : 1;
  return natural.map((width) => ({ width: Math.max(28, width * scale) }));
}

interface PdfObject {
  readonly body: string;
}

/** Assemble the document with byte-exact offsets (the xref contract). */
function assemblePdf(objects: readonly PdfObject[]): Buffer {
  const chunks: Buffer[] = [];
  const offsets: number[] = [];
  let position = 0;
  const push = (buffer: Buffer): void => {
    chunks.push(buffer);
    position += buffer.length;
  };
  push(Buffer.from("%PDF-1.4\n", "latin1"));
  for (let i = 0; i < objects.length; i += 1) {
    offsets.push(position);
    push(Buffer.from(`${i + 1} 0 obj\n${objects[i]!.body}\nendobj\n`, "latin1"));
  }
  const xrefStart = position;
  const xrefLines = [`xref\n0 ${objects.length + 1}\n`, "0000000000 65535 f \n"];
  for (const offset of offsets) {
    xrefLines.push(`${offset.toString().padStart(10, "0")} 00000 n \n`);
  }
  push(Buffer.from(xrefLines.join(""), "latin1"));
  const trailer = `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;
  push(Buffer.from(trailer, "latin1"));
  return Buffer.concat(chunks);
}

function pageContentStream(
  input: PdfTableInput,
  columns: readonly ColumnLayout[],
  rows: readonly (readonly CsvCell[])[],
  pageNumber: number,
  totalPages: number,
): string {
  const ops: string[] = [];
  let cursorY = PAGE_HEIGHT - MARGIN;
  ops.push(`BT /F2 ${TITLE_SIZE} Tf ${MARGIN} ${cursorY} Td (${pdfEscape(input.title)}) Tj ET`);
  cursorY -= 16;
  const subtitle = `${input.subtitle ?? "Generated by PROFIT TOOL AI"}  ·  Page ${pageNumber} of ${totalPages}`;
  ops.push(`BT /F1 ${BODY_SIZE} Tf ${MARGIN} ${cursorY} Td (${pdfEscape(subtitle)}) Tj ET`);
  cursorY -= HEADER_GAP;

  const tableWidth = columns.reduce((sum, col) => sum + col.width, 0);
  // Header row.
  ops.push(`${MARGIN} ${cursorY - ROW_HEIGHT + 3} ${tableWidth} ${ROW_HEIGHT} re f 0.92 g`);
  ops.push("0 g");
  let cursorX = MARGIN;
  for (let i = 0; i < input.headers.length; i += 1) {
    const text = truncateToWidth(input.headers[i]!, columns[i]!.width - 6, BODY_SIZE);
    ops.push(`BT /F2 ${BODY_SIZE} Tf ${cursorX + 3} ${cursorY - ROW_HEIGHT + 7} Td (${pdfEscape(text)}) Tj ET`);
    cursorX += columns[i]!.width;
  }
  cursorY -= ROW_HEIGHT;

  for (const row of rows) {
    cursorX = MARGIN;
    for (let i = 0; i < input.headers.length; i += 1) {
      const text = truncateToWidth(cellText(row[i] ?? null), columns[i]!.width - 6, BODY_SIZE);
      ops.push(`BT /F1 ${BODY_SIZE} Tf ${cursorX + 3} ${cursorY - ROW_HEIGHT + 7} Td (${pdfEscape(text)}) Tj ET`);
      cursorX += columns[i]!.width;
    }
    // Hairline rule under the row.
    ops.push(`${MARGIN} ${cursorY - ROW_HEIGHT} ${tableWidth} 0.4 re f 0.88 g`);
    ops.push("0 g");
    cursorY -= ROW_HEIGHT;
  }
  return ops.join("\n");
}

/** Build the full PDF buffer (paginated table, header repeated per page). */
export function buildPdf(input: PdfTableInput): Buffer {
  if (input.headers.length === 0 || input.headers.length > MAX_COLUMNS) {
    throw new Error(`pdf: header count must be 1..${MAX_COLUMNS}`);
  }
  const columns = computeColumnWidths(input.headers, input.rows);
  const firstPageTop = PAGE_HEIGHT - MARGIN - 16 - HEADER_GAP;
  const rowsPerPage = Math.max(1, Math.floor((firstPageTop - MARGIN - ROW_HEIGHT) / ROW_HEIGHT));

  const pages: (readonly CsvCell[])[][] = [];
  for (let start = 0; start < input.rows.length; start += rowsPerPage) {
    pages.push(input.rows.slice(start, start + rowsPerPage));
  }
  if (pages.length === 0) pages.push([]);

  const objects: PdfObject[] = [];
  // Object 1: catalog. Object 2: pages. Objects 3..: per-page page+content pairs.
  const pageObjectIds: number[] = [];
  let nextId = 3;
  for (let p = 0; p < pages.length; p += 1) {
    pageObjectIds.push(nextId);
    nextId += 2;
  }
  // Font objects land after page objects.
  const fontRegularId = nextId;
  const fontBoldId = nextId + 1;

  objects.push({ body: "<< /Type /Catalog /Pages 2 0 R >>" });
  const kids = pageObjectIds.map((id) => `${id} 0 R`).join(" ");
  objects.push({ body: `<< /Type /Pages /Kids [ ${kids} ] /Count ${pageObjectIds.length} >>` });

  for (let p = 0; p < pages.length; p += 1) {
    const pageId = pageObjectIds[p]!;
    const contentId = pageId + 1;
    const stream = pageContentStream(input, columns, pages[p]!, p + 1, pageObjectIds.length);
    objects.push({
      body: `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${fontRegularId} 0 R /F2 ${fontBoldId} 0 R >> >> /Contents ${contentId} 0 R >>`,
    });
    objects.push({
      body: `<< /Length ${Buffer.byteLength(stream, "latin1")} >>\nstream\n${stream}\nendstream`,
    });
  }
  objects.push({ body: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>" });
  objects.push({ body: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>" });

  return assemblePdf(objects);
}

/* ── Multi-section documents (M8 enterprise reports — ADR 34) ────────────── */

export interface PdfSection {
  readonly heading: string;
  readonly paragraphs: readonly string[];
  readonly table: { readonly headers: readonly string[]; readonly rows: readonly (readonly CsvCell[])[] } | null;
}

export interface PdfDocumentInput {
  readonly title: string;
  readonly subtitle: string;
  readonly sections: readonly PdfSection[];
}

const HEADING_SIZE = 10;
const PARA_LINE_HEIGHT = 11;
const SECTION_GAP = 8;

/** Word-wrap to the page width at the given size (pre-sanitized text). */
function wrapText(value: string, size: number): string[] {
  const widthPt = PAGE_WIDTH - MARGIN * 2;
  const maxChars = Math.max(8, Math.floor(widthPt / (size * CHAR_WIDTH_FACTOR)));
  const words = sanitizeText(value).split(/\s+/).filter((word) => word.length > 0);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const candidate = current.length === 0 ? word : `${current} ${word}`;
    if (sanitizeText(candidate).length <= maxChars) {
      current = candidate;
    } else {
      if (current.length > 0) lines.push(current);
      // A single over-wide word hard-truncates like table cells do.
      current = truncateToWidth(word, widthPt, size);
    }
  }
  if (current.length > 0) lines.push(current);
  return lines.slice(0, 40); // bounded — a section never floods a report
}

interface PageOps {
  readonly ops: string[];
}

/** Lay the whole document out as paginated content ops (tables carry headers). */
function layoutDocument(input: PdfDocumentInput): PageOps[] {
  const pages: { ops: string[] }[] = [];
  let ops: string[] = [];
  let cursorY = 0;

  const startPage = (): void => {
    ops = [];
    // Every page begins below the title + subtitle band.
    cursorY = PAGE_HEIGHT - MARGIN - 16 - HEADER_GAP;
  };
  startPage();
  const pageBreak = (): void => {
    pages.push({ ops });
    startPage();
  };
  const ensure = (needed: number): void => {
    if (cursorY - needed < MARGIN) pageBreak();
  };

  for (const section of input.sections) {
    ensure(HEADING_SIZE + SECTION_GAP + ROW_HEIGHT);
    ops.push(`BT /F2 ${HEADING_SIZE} Tf ${MARGIN} ${cursorY} Td (${pdfEscape(section.heading)}) Tj ET`);
    cursorY -= HEADING_SIZE + 6;
    for (const paragraph of section.paragraphs) {
      for (const line of wrapText(paragraph, BODY_SIZE)) {
        ensure(PARA_LINE_HEIGHT);
        ops.push(`BT /F1 ${BODY_SIZE} Tf ${MARGIN} ${cursorY} Td (${pdfEscape(line)}) Tj ET`);
        cursorY -= PARA_LINE_HEIGHT;
      }
      cursorY -= 2;
    }
    const table = section.table;
    if (table !== null && table.headers.length > 0) {
      if (table.headers.length > MAX_COLUMNS) {
        throw new Error(`pdf: header count must be 1..${MAX_COLUMNS}`);
      }
      const columns = computeColumnWidths(table.headers, table.rows);
      const tableWidth = columns.reduce((sum, col) => sum + col.width, 0);
      const drawHeader = (): void => {
        ops.push(`${MARGIN} ${cursorY - ROW_HEIGHT + 3} ${tableWidth} ${ROW_HEIGHT} re f 0.92 g`);
        ops.push("0 g");
        let cursorX = MARGIN;
        for (let i = 0; i < table.headers.length; i += 1) {
          const text = truncateToWidth(table.headers[i]!, columns[i]!.width - 6, BODY_SIZE);
          ops.push(`BT /F2 ${BODY_SIZE} Tf ${cursorX + 3} ${cursorY - ROW_HEIGHT + 7} Td (${pdfEscape(text)}) Tj ET`);
          cursorX += columns[i]!.width;
        }
        cursorY -= ROW_HEIGHT;
      };
      ensure(ROW_HEIGHT * 2);
      drawHeader();
      for (const row of table.rows) {
        ensure(ROW_HEIGHT);
        if (ops.length === 0) drawHeader(); // fresh page mid-table: repeat header
        let cursorX = MARGIN;
        for (let i = 0; i < table.headers.length; i += 1) {
          const text = truncateToWidth(cellText(row[i] ?? null), columns[i]!.width - 6, BODY_SIZE);
          ops.push(`BT /F1 ${BODY_SIZE} Tf ${cursorX + 3} ${cursorY - ROW_HEIGHT + 7} Td (${pdfEscape(text)}) Tj ET`);
          cursorX += columns[i]!.width;
        }
        ops.push(`${MARGIN} ${cursorY - ROW_HEIGHT} ${tableWidth} 0.4 re f 0.88 g`);
        ops.push("0 g");
        cursorY -= ROW_HEIGHT;
      }
    }
    cursorY -= SECTION_GAP;
  }
  pages.push({ ops });
  return pages;
}

/**
 * Multi-section report PDF: one flow document (headings, wrapped paragraphs,
 * tables with repeated headers across page breaks). Title/subtitle render on
 * every page with page numbering, like the single-table writer.
 */
export function buildPdfDocument(input: PdfDocumentInput): Buffer {
  if (input.sections.length === 0) throw new Error("pdf: document needs at least one section");
  const flows = layoutDocument(input);
  const objects: PdfObject[] = [];
  const pageObjectIds: number[] = [];
  let nextId = 3;
  for (let p = 0; p < flows.length; p += 1) {
    pageObjectIds.push(nextId);
    nextId += 2;
  }
  const fontRegularId = nextId;
  const fontBoldId = nextId + 1;

  objects.push({ body: "<< /Type /Catalog /Pages 2 0 R >>" });
  const kids = pageObjectIds.map((id) => `${id} 0 R`).join(" ");
  objects.push({ body: `<< /Type /Pages /Kids [ ${kids} ] /Count ${pageObjectIds.length} >>` });

  for (let p = 0; p < flows.length; p += 1) {
    const topOps = [
      `BT /F2 ${TITLE_SIZE} Tf ${MARGIN} ${PAGE_HEIGHT - MARGIN} Td (${pdfEscape(input.title)}) Tj ET`,
      `BT /F1 ${BODY_SIZE} Tf ${MARGIN} ${PAGE_HEIGHT - MARGIN - 16} Td (${pdfEscape(`${input.subtitle}  ·  Page ${p + 1} of ${flows.length}`)}) Tj ET`,
    ];
    const stream = [...topOps, ...flows[p]!.ops].join("\n");
    const pageId = pageObjectIds[p]!;
    objects.push({
      body: `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${fontRegularId} 0 R /F2 ${fontBoldId} 0 R >> >> /Contents ${pageId + 1} 0 R >>`,
    });
    objects.push({
      body: `<< /Length ${Buffer.byteLength(stream, "latin1")} >>\nstream\n${stream}\nendstream`,
    });
  }
  objects.push({ body: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>" });
  objects.push({ body: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>" });
  return assemblePdf(objects);
}
