import {
  and,
  asc,
  desc,
  eq,
  gte,
  isNull,
  lt,
  sql,
  withStoreScope,
  auditLogs,
  exportsTable,
  recommendations,
  shopifyCustomers,
  shopifyOrders,
  shopifyProducts,
  users,
} from "@profit/db";
import type { ProfitDb } from "@profit/db";
import { ExportFormat, ExportKind, ExportStatus } from "@profit/types";
import { z } from "zod";
import { buildCsv, type CsvCell } from "./export/csv";
import { buildXlsx } from "./export/xlsx";
import { buildPdf } from "./export/pdf";

/**
 * ExportService (M6): merchant-requested report files. Rows are built from
 * the tenant-scoped replica (RLS-enforced), capped by EXPORT_MAX_ROWS, and
 * the generated bytes live in the exports row (no object-storage dependency
 * at this scale — documented in the M6 doc trade-offs). Expiry sweeps null
 * the bytes but keep provenance rows.
 */

export const EXPORT_LIMITS = {
  maxRows: 50_000,
  retentionDays: 7,
  pageSize: 5_000,
  maxFileBytes: 24 * 1024 * 1024,
} as const;

const exportParamsSchema = z
  .object({
    from: z.string().datetime({ offset: true }).optional(),
    to: z.string().datetime({ offset: true }).optional(),
  })
  .strict();
export type ExportParams = z.infer<typeof exportParamsSchema>;

export class ExportNotFoundError extends Error {
  constructor(id: string) {
    super(`export ${id} not found`);
    this.name = "ExportNotFoundError";
  }
}

export class ExportStateError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ExportStateError";
  }
}

export class ExportTooLargeError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ExportTooLargeError";
  }
}

export interface ExportRow {
  readonly id: string;
  readonly requestedByUserId: string | null;
  readonly kind: (typeof ExportKind)[keyof typeof ExportKind];
  readonly format: (typeof ExportFormat)[keyof typeof ExportFormat];
  readonly status: (typeof ExportStatus)[keyof typeof ExportStatus];
  readonly params: unknown;
  readonly fileName: string | null;
  readonly rowCount: number | null;
  readonly sizeBytes: number | null;
  readonly error: string | null;
  readonly expiresAt: Date | null;
  readonly completedAt: Date | null;
  readonly createdAt: Date;
}

interface BuiltReport {
  readonly headers: readonly string[];
  readonly rows: readonly (readonly CsvCell[])[];
}

const MIME_BY_FORMAT = {
  [ExportFormat.Csv]: "text/csv; charset=utf-8",
  [ExportFormat.Xlsx]: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  [ExportFormat.Pdf]: "application/pdf",
} as const;

const EXTENSION_BY_FORMAT = {
  [ExportFormat.Csv]: "csv",
  [ExportFormat.Xlsx]: "xlsx",
  [ExportFormat.Pdf]: "pdf",
} as const;

export function mimeForFormat(format: (typeof ExportFormat)[keyof typeof ExportFormat]): string {
  return MIME_BY_FORMAT[format];
}

export class ExportService {
  constructor(private readonly db: ProfitDb) {}

  /** Register an export request (QUEUED); the worker materializes it. */
  async request(
    storeId: string,
    input: {
      kind: (typeof ExportKind)[keyof typeof ExportKind];
      format: (typeof ExportFormat)[keyof typeof ExportFormat];
      params?: unknown;
      requestedByUserId: string | null;
    },
    now = new Date(),
  ): Promise<ExportRow> {
    const params = exportParamsSchema.parse(input.params ?? {});
    if (params.from !== undefined && params.to !== undefined && params.from > params.to) {
      throw new ExportStateError("params.from must be before params.to");
    }
    return withStoreScope(this.db, storeId, async (tx) => {
      const active = await tx
        .select({ total: sql<number>`count(*)::int` })
        .from(exportsTable)
        .where(
          and(
            eq(exportsTable.storeId, storeId),
            sql`${exportsTable.status} IN (${ExportStatus.Queued}, ${ExportStatus.Running})`,
          ),
        );
      if ((active[0]?.total ?? 0) >= 5) {
        throw new ExportStateError("too many exports in progress — wait for one to finish");
      }
      const rows = await tx
        .insert(exportsTable)
        .values({
          storeId,
          requestedByUserId: input.requestedByUserId,
          kind: input.kind,
          format: input.format,
          status: ExportStatus.Queued,
          params,
          expiresAt: null,
        })
        .returning();
      const row = rows[0];
      if (row === undefined) throw new ExportStateError("export insert returned no row");
      void now;
      return this.toRow(row);
    });
  }

  /** Single export row for detail/notify lookups (null when foreign or absent). */
  async getExport(storeId: string, exportId: string): Promise<ExportRow | null> {
    return withStoreScope(this.db, storeId, async (tx) => {
      const rows = await tx
        .select()
        .from(exportsTable)
        .where(and(eq(exportsTable.id, exportId), eq(exportsTable.storeId, storeId)))
        .limit(1);
      const row = rows[0];
      return row === undefined ? null : this.toRow(row);
    });
  }

  async list(storeId: string, page: number, pageSize: number): Promise<{ readonly rows: readonly ExportRow[]; readonly total: number }> {
    return withStoreScope(this.db, storeId, async (tx) => {
      const rows = await tx
        .select()
        .from(exportsTable)
        .where(eq(exportsTable.storeId, storeId))
        .orderBy(desc(exportsTable.createdAt))
        .limit(pageSize)
        .offset((page - 1) * pageSize);
      const totals = await tx
        .select({ total: sql<number>`count(*)::int` })
        .from(exportsTable)
        .where(eq(exportsTable.storeId, storeId));
      return { rows: rows.map((r) => this.toRow(r)), total: totals[0]?.total ?? 0 };
    });
  }

  /** Download payload for a READY, unexpired export. */
  async loadFile(
    storeId: string,
    exportId: string,
  ): Promise<{ readonly fileName: string; readonly mime: string; readonly data: Buffer }> {
    return withStoreScope(this.db, storeId, async (tx) => {
      const rows = await tx
        .select({
          fileName: exportsTable.fileName,
          fileData: exportsTable.fileData,
          status: exportsTable.status,
          format: exportsTable.format,
          expiresAt: exportsTable.expiresAt,
        })
        .from(exportsTable)
        .where(and(eq(exportsTable.id, exportId), eq(exportsTable.storeId, storeId)))
        .limit(1);
      const row = rows[0];
      if (row === undefined) throw new ExportNotFoundError(exportId);
      if (row.status !== ExportStatus.Ready) throw new ExportStateError(`export is ${row.status}, not READY`);
      if (row.fileData === null) throw new ExportStateError("export file has expired — request a fresh one");
      if (row.fileName === null) throw new ExportStateError("export metadata incomplete");
      // Driver normalization at the edge: postgres.js hands bytea back as a
      // Buffer, PGlite as a Uint8Array — both are byte sources (same pattern
      // the DB timestamps-normalization follows).
      const data = Buffer.isBuffer(row.fileData)
        ? row.fileData
        : Buffer.from(row.fileData as unknown as Uint8Array);
      return { fileName: row.fileName, mime: mimeForFormat(row.format), data };
    });
  }

  /**
   * QUEUED→RUNNING (CAS) → build → READY | FAILED. Runs tenant-scoped for
   * row reads; the final bytea write rides the same scope (store-owned row).
   */
  async generate(storeId: string, exportId: string, now = new Date()): Promise<{ readonly generated: boolean }> {
    const claimed = await withStoreScope(this.db, storeId, async (tx) => {
      const updated = await tx
        .update(exportsTable)
        .set({ status: ExportStatus.Running, updatedAt: now })
        .where(and(eq(exportsTable.id, exportId), eq(exportsTable.status, ExportStatus.Queued)))
        .returning({
          kind: exportsTable.kind,
          format: exportsTable.format,
          params: exportsTable.params,
        });
      return updated[0] ?? null;
    });
    if (claimed === null) return { generated: false };

    try {
      const params = exportParamsSchema.parse(claimed.params ?? {});
      const report = await this.buildReport(storeId, claimed.kind, params);
      const { buffer, fileName } = this.render(claimed.kind, claimed.format, report, now);
      if (buffer.length > EXPORT_LIMITS.maxFileBytes) {
        throw new ExportTooLargeError(`report exceeds ${EXPORT_LIMITS.maxFileBytes} bytes — narrow the filters`);
      }
      await withStoreScope(this.db, storeId, async (tx) => {
        await tx
          .update(exportsTable)
          .set({
            status: ExportStatus.Ready,
            fileName,
            fileData: buffer,
            rowCount: report.rows.length,
            sizeBytes: buffer.length,
            completedAt: now,
            expiresAt: new Date(now.getTime() + EXPORT_LIMITS.retentionDays * 86_400_000),
            updatedAt: now,
          })
          .where(eq(exportsTable.id, exportId));
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : "unknown export error";
      await withStoreScope(this.db, storeId, async (tx) => {
        await tx
          .update(exportsTable)
          .set({ status: ExportStatus.Failed, error: message.slice(0, 500), completedAt: now, updatedAt: now })
          .where(eq(exportsTable.id, exportId));
      });
    }
    return { generated: true };
  }

  /** Expired READY exports lose their bytes (TICK sweep — owner role). */
  async sweepExpired(now = new Date()): Promise<number> {
    const updated = await this.db
      .update(exportsTable)
      .set({ fileData: null, updatedAt: now })
      .where(
        and(
          eq(exportsTable.status, ExportStatus.Ready),
          sql`${exportsTable.expiresAt} IS NOT NULL`,
          lt(exportsTable.expiresAt, now),
          sql`${exportsTable.fileData} IS NOT NULL`,
        ),
      )
      .returning({ id: exportsTable.id });
    return updated.length;
  }

  /* ─── report builders (tenant-scoped, capped) ───────────────────── */

  private async buildReport(
    storeId: string,
    kind: (typeof ExportKind)[keyof typeof ExportKind],
    params: ExportParams,
  ): Promise<BuiltReport> {
    switch (kind) {
      case ExportKind.AuditLogs:
        return this.buildAuditLogs(storeId, params);
      case ExportKind.Customers:
        return this.buildCustomers(storeId);
      case ExportKind.Orders:
        return this.buildOrders(storeId, params);
      case ExportKind.Products:
        return this.buildProducts(storeId);
      case ExportKind.Recommendations:
        return this.buildRecommendations(storeId, params);
    }
  }

  private dateRange(params: ExportParams): { from: Date | null; to: Date | null } {
    return {
      from: params.from !== undefined ? new Date(params.from) : null,
      to: params.to !== undefined ? new Date(params.to) : null,
    };
  }

  private async buildAuditLogs(storeId: string, params: ExportParams): Promise<BuiltReport> {
    const { from, to } = this.dateRange(params);
    return withStoreScope(this.db, storeId, async (tx) => {
      const conditions = [eq(auditLogs.storeId, storeId)];
      if (from !== null) conditions.push(gte(auditLogs.createdAt, from));
      if (to !== null) conditions.push(lt(auditLogs.createdAt, to));
      const rows = await tx
        .select({
          createdAt: auditLogs.createdAt,
          action: auditLogs.action,
          entityType: auditLogs.entityType,
          entityId: auditLogs.entityId,
          actor: users.email,
          result: auditLogs.result,
          ip: auditLogs.ip,
        })
        .from(auditLogs)
        .leftJoin(users, eq(auditLogs.userId, users.id))
        .where(and(...conditions))
        .orderBy(asc(auditLogs.createdAt))
        .limit(EXPORT_LIMITS.maxRows);
      return {
        headers: ["Timestamp (UTC)", "Action", "Entity Type", "Entity ID", "Actor", "Result", "IP"],
        rows: rows.map((r) => [
          r.createdAt.toISOString(),
          r.action,
          r.entityType ?? "",
          r.entityId ?? "",
          r.actor ?? "system",
          r.result,
          r.ip ?? "",
        ]),
      };
    });
  }

  private async buildCustomers(storeId: string): Promise<BuiltReport> {
    return withStoreScope(this.db, storeId, async (tx) => {
      const rows = await tx
        .select({
          email: shopifyCustomers.email,
          firstName: shopifyCustomers.firstName,
          lastName: shopifyCustomers.lastName,
          phone: shopifyCustomers.phone,
          ordersCount: shopifyCustomers.ordersCount,
          totalSpent: shopifyCustomers.totalSpent,
          acceptsMarketing: shopifyCustomers.acceptsMarketing,
          tags: shopifyCustomers.tags,
          createdAt: shopifyCustomers.createdAt,
        })
        .from(shopifyCustomers)
        .where(and(eq(shopifyCustomers.storeId, storeId), isNull(shopifyCustomers.deletedAt)))
        .orderBy(asc(shopifyCustomers.createdAt))
        .limit(EXPORT_LIMITS.maxRows);
      return {
        headers: ["Email", "First Name", "Last Name", "Phone", "Orders", "Total Spent", "Accepts Marketing", "Tags", "Synced At (UTC)"],
        rows: rows.map((r) => [
          r.email ?? "",
          r.firstName ?? "",
          r.lastName ?? "",
          r.phone ?? "",
          r.ordersCount,
          r.totalSpent,
          r.acceptsMarketing ? "yes" : "no",
          r.tags.join(", "),
          r.createdAt.toISOString(),
        ]),
      };
    });
  }

  private async buildOrders(storeId: string, params: ExportParams): Promise<BuiltReport> {
    const { from, to } = this.dateRange(params);
    return withStoreScope(this.db, storeId, async (tx) => {
      const conditions = [eq(shopifyOrders.storeId, storeId)]; // shopify_orders is hard-delete-free (softDeleteColumns absent by schema design)
      if (from !== null) conditions.push(sql`${shopifyOrders.processedAt} >= ${from}`);
      if (to !== null) conditions.push(sql`${shopifyOrders.processedAt} < ${to}`);
      const rows = await tx
        .select({
          name: shopifyOrders.name,
          email: shopifyOrders.email,
          financialStatus: shopifyOrders.financialStatus,
          fulfillmentStatus: shopifyOrders.fulfillmentStatus,
          currency: shopifyOrders.currency,
          totalPrice: shopifyOrders.totalPrice,
          totalDiscounts: shopifyOrders.totalDiscounts,
          totalRefunded: shopifyOrders.totalRefunded,
          processedAt: shopifyOrders.processedAt,
        })
        .from(shopifyOrders)
        .where(and(...conditions))
        .orderBy(asc(shopifyOrders.processedAt))
        .limit(EXPORT_LIMITS.maxRows);
      return {
        headers: ["Order", "Customer Email", "Financial", "Fulfillment", "Currency", "Total", "Discounts", "Refunded", "Processed At (UTC)"],
        rows: rows.map((r) => [
          r.name,
          r.email ?? "",
          r.financialStatus ?? "",
          r.fulfillmentStatus ?? "unfulfilled",
          r.currency,
          r.totalPrice,
          r.totalDiscounts,
          r.totalRefunded,
          r.processedAt?.toISOString() ?? "",
        ]),
      };
    });
  }

  private async buildProducts(storeId: string): Promise<BuiltReport> {
    return withStoreScope(this.db, storeId, async (tx) => {
      const rows = await tx
        .select({
          title: shopifyProducts.title,
          handle: shopifyProducts.handle,
          status: shopifyProducts.status,
          vendor: shopifyProducts.vendor,
          productType: shopifyProducts.productType,
          tags: shopifyProducts.tags,
          createdAt: shopifyProducts.createdAt,
        })
        .from(shopifyProducts)
        .where(and(eq(shopifyProducts.storeId, storeId), isNull(shopifyProducts.deletedAt)))
        .orderBy(asc(shopifyProducts.title))
        .limit(EXPORT_LIMITS.maxRows);
      return {
        headers: ["Title", "Handle", "Status", "Vendor", "Type", "Tags", "Synced At (UTC)"],
        rows: rows.map((r) => [
          r.title,
          r.handle ?? "",
          r.status,
          r.vendor ?? "",
          r.productType ?? "",
          r.tags.join(", "),
          r.createdAt.toISOString(),
        ]),
      };
    });
  }

  private async buildRecommendations(storeId: string, params: ExportParams): Promise<BuiltReport> {
    const { from, to } = this.dateRange(params);
    return withStoreScope(this.db, storeId, async (tx) => {
      const conditions = [eq(recommendations.storeId, storeId)];
      if (from !== null) conditions.push(gte(recommendations.createdAt, from));
      if (to !== null) conditions.push(lt(recommendations.createdAt, to));
      const rows = await tx
        .select({
          type: recommendations.type,
          title: recommendations.title,
          status: recommendations.status,
          priority: recommendations.priority,
          confidence: recommendations.confidence,
          estimatedRevenueCents: recommendations.estimatedRevenueCents,
          createdAt: recommendations.createdAt,
        })
        .from(recommendations)
        .where(and(...conditions))
        .orderBy(desc(recommendations.createdAt))
        .limit(EXPORT_LIMITS.maxRows);
      return {
        headers: ["Type", "Title", "Status", "Priority", "Confidence", "Est. Revenue", "Created At (UTC)"],
        rows: rows.map((r) => [
          r.type,
          r.title,
          r.status,
          r.priority,
          r.confidence,
          `$${(r.estimatedRevenueCents / 100).toFixed(2)}`,
          r.createdAt.toISOString(),
        ]),
      };
    });
  }

  private render(
    kind: (typeof ExportKind)[keyof typeof ExportKind],
    format: (typeof ExportFormat)[keyof typeof ExportFormat],
    report: BuiltReport,
    now: Date,
  ): { buffer: Buffer; fileName: string } {
    const stamp = now.toISOString().slice(0, 10);
    const base = `profit-tool-${kind.toLowerCase().replaceAll("_", "-")}-${stamp}`;
    switch (format) {
      case ExportFormat.Csv:
        return { buffer: buildCsv(report.headers, report.rows), fileName: `${base}.${EXTENSION_BY_FORMAT[format]}` };
      case ExportFormat.Xlsx:
        return { buffer: buildXlsx(report.headers, report.rows), fileName: `${base}.${EXTENSION_BY_FORMAT[format]}` };
      case ExportFormat.Pdf:
        return {
          buffer: buildPdf({
            title: `PROFIT TOOL AI — ${kind.toLowerCase().replaceAll("_", " ")} export`,
            subtitle: `Generated ${now.toISOString()} · ${report.rows.length} rows`,
            headers: report.headers,
            rows: report.rows,
          }),
          fileName: `${base}.${EXTENSION_BY_FORMAT[format]}`,
        };
    }
  }

  private toRow(row: typeof exportsTable.$inferSelect): ExportRow {
    const { storeId: _storeId, fileData: _fileData, updatedAt: _updatedAt, ...rest } = row;
    return rest;
  }
}
